server:
  port: 8081
  context-path: /
logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG
wx:
  mp:
    configs:
      - appId: wx4b897a469fa42b2f
        secret: fe01032c2e1ae5571b18f5be16f5c97e
        token: hellobird
        aesKey: blYMpy7JlNnBg8qHdKFDEMct0ggqTNDKrLpzII0sTHX
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.14.113.218:3376/springboot?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: 123!@#456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    mode: LEGACYHTML5 #thymeleaf单标记问题
    cache: false #关闭thymeleaf缓存
    encoding: utf-8
    content-type: text/html
  jackson:
    default-property-inclusion: non_null #输入json的时候，如果有属性值为null而不打印该属性
  messages: #国际化配置文件
    basename: messages
    encoding: UTF-8
  mvc:
    view:
     static-path-pattern: /**
     suffix: .html
mybatis:
  type-aliases-package: com.hang.common.domain #指定domain类的基包
  mapper-locations: classpath:mapper/*.xml #指定*Mapper.xml的位置
  config-location: classpath:mybatis-config.xml
  check-config-location: true